import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-bookinglist',
  templateUrl: './bookinglist.component.html',
  styleUrls: ['./bookinglist.component.css']
})
export class BookinglistComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  shipmentCommon=[
    {  
      bookingno:120897001487,
      'portStart':"SAV",
      'portStartPlace':'Savannah',
      'startDate':"Tue,09 May'17",
      'portEnd':"MAA",
      'portEndPlace':'Savannah',
      'EndDate':"Tue,09 May'17",
      'departedfrom':'Chennai Airport ',
      'shipportone':'Elantas PDG inc ',
      'shipporttwo':"SAV",
      'shipportthree':'Elantas PDG inc ',
      'shipportfour':"SIN",
      'shipportfiver':"PKG",
      'shippingimage':`<i class="fas fa-fighter-jet"></i>` ,
      'totaldays':"12 days",
      'shipper':'IDI FABRICATION INC',
      'consignee':'COMSTER AUTOMATIVE TECHNOLOGIES PVT LTD',
      'image':"../../../assets/boat.png",
      collectiontype:'Collect',
      amount:25000,
    },
    { 
      bookingno:120897001488,
      'portStart':"BOM",
      'portStartPlace':'Mumbai',
      'startDate':"Tue,09 May'17",
      'portEnd':"DXB",
      'portEndPlace':'Dubai',
      'EndDate':"Tue,09 May'17",
      'departedfrom':'Actual Shedule ',
      'shipportone':'Mepz Lab ',
      'shipporttwo':"BOM",
      'shipportthree':'PNQ ',
      'shipportfour':"Zenth Fuzin",
      'shipportfiver':"PKG",
      'totaldays':"14 days",
      'shipper':'ROTOR CLIP COMPANY',
      'consignee':'COMSTER AUTOMATIVE TECHNOLOGIES PVT LTD',
      'image':"../../../assets/flight (1).png",
      collectiontype:'Prepaid',
      amount:25000,
    },
    {
      bookingno:120897001489,
      'portStart':"SAV",
      'portStartPlace':'Savannah',
      'startDate':"Tue,09 May'17",
      'portEnd':"SAV",
      'portEndPlace':'Mumbai',
      'EndDate':"Tue,09 May'17",
      'departedfrom':'Chennai Airport ',
      'shipportone':'Elantas PDG inc ',
      'shipporttwo':"SAV",
      'shipportthree':'Elantas PDG inc ',
      'shipportfour':"SIN",
      'shipportfiver':"PKG",
      'totaldays':"11 days",
      'shipper':'ADVANCED DECORATIVE SYSTEM (SHANGAI)CO LTD',
      'consignee':'COMSTER AUTOMATIVE TECHNOLOGIES PVT LTD',
      'image':"../../../assets/boat.png",
      collectiontype:'Collect',
      amount:20000,
    },
    {  
      bookingno:120897001490,
      'portStart':"SAV",
      'portStartPlace':'Savannah',
      'startDate':"Tue,09 May'17",
      'portEnd':"MAA",
      'portEndPlace':'Chennai',
      'EndDate':"Tue,09 May'17",
      'departedfrom':'Chennai Airport ',
      'shipportone':'Elantas PDG inc ',
      'shipporttwo':"SAV",
      'shipportthree':'Elantas PDG inc ',
      'shipportfour':"SIN",
      'shipportfiver':"PKG",
      'totaldays':"12 days",
      'shipper':'ELANDAS PDG INC',
      'consignee':'COMSTER AUTOMATIVE TECHNOLOGIES PVT LTD',
      'image':"../../../assets/flight (1).png",
      collectiontype:'Prepaid',
      amount:45000,
    },
    {  
      bookingno:120897001491,
      'portStart':"BOM",
      'portStartPlace':'Mumbai',
      'startDate':"Tue,09 May'17",
      'portEnd':"DXB",
      'portEndPlace':'Dubai',
      'EndDate':"Tue,09 May'17",
      'departedfrom':'Actual Shedule ',
      'shipportone':'Mepz Lab ',
      'shipporttwo':"BOM",
      'shipportthree':'PNQ ',
      'shipportfour':"Zenth Fuzin",
      'shipportfiver':"PKG",
      'totaldays':"10 days",
      'shipper':'MAHLE AFTERMARKET  S DE RL DE CV',
      'consignee':'COMSTER AUTOMATIVE TECHNOLOGIES PVT LTD',
      'image':"../../../assets/boat.png",
      collectiontype:'Collect',
      amount:35000,
    },
    { 
      bookingno:120897001492,
      'portStart':"SAV",
      'portStartPlace':'Savannah',
      'startDate':"Tue,09 May'17",
      'portEnd':"SAV",
      'portEndPlace':'Mumbai',
      'EndDate':"Tue,09 May'17",
      'departedfrom':'Chennai Airport ',
      'shipportone':'Elantas PDG inc ',
      'shipporttwo':"SAV",
      'shipportthree':'Elantas PDG inc ',
      'shipportfour':"SIN",
      'shipportfiver':"PKG",
      'totaldays':"18 days",
      'shipper':'MNP COPORATION',
      'consignee':'COMSTER AUTOMATIVE TECHNOLOGIES PVT LTD',
      'image':"../../../assets/flight (1).png",
      collectiontype:'Prepaid',
      amount:30000,
    },
  ]

}
